# Generated by Django 2.2.3 on 2020-03-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burials',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('lot', models.CharField(blank=True, max_length=50)),
                ('grave', models.CharField(blank=True, max_length=50)),
                ('form_type', models.CharField(blank=True, max_length=50)),
                ('time', models.DateTimeField(null=True)),
                ('image_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
