# Generated by Django 2.2.3 on 2020-03-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burials',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
